### ISSUE TITLE
Excelente colección de banderas en formato PNG sin padding ni borde

### ISSUE THREAD

**Issue by SparcV8** [yammadev/flag-icons#1]
Felíz semana,
hasta hoy he creido que "ISSUE" = error/problema
Sin embargo me dícen que el mejor lugar para publicar una reseña es en el enláce "ISSUE".

Las banderas de ésta distribución son EXCELENTES,
en otros lugares faltan o son feas.

De hecho,llegué hasta aquí buscando la condenada bandera de CURAZAO (CW).

No la conseguía en BUEN formato hasta llegar aquí.

Espero que sigan manteniendo éste proyecto.

Muchas gracias!

Felíz MAYO REVOLUCIONARIO!

**Comment by yammadev** [comment]
@SparcV8 Gracias por tu comentario. Genial que puedas usar la bandera de Curaçao <img src='https://raw.githubusercontent.com/yammadev/flag-icons/master/png/CW%402x.png' width='21' height='15'>

Definitivamente seguiré manteniendo el producto, he estado actualizándolo y espero que más personas en el mundo <img src='https://raw.githubusercontent.com/yammadev/flag-icons/master/png/WW.png' width='21' height='15'> puedan usarlo. 

Gracias, y saludos desde Colombia <img src='https://raw.githubusercontent.com/yammadev/flag-icons/master/png/CO%402x.png' width='21' height='15'>

**Comment by yammadev** [comment]
> hasta hoy he creido que "ISSUE" = error/problema. Sin embargo me dícen que el mejor lugar para publicar una reseña es en el enláce "ISSUE".

@SparcV8, A propósito de eso, recientemente Github en su evento Satellite 2020 ha anunciado el lanzamiento de [Github Discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) *A new way for software communities to collaborate outside the codebase*.

Así que pronto esto estará disponible.

Saludos,

**Comment by SparcV8** [comment]
Buen día ingeniero,
por favor compartanos la curiosidad acerca de

""" yammadev """

a qué se refiere ése string?

**Comment by yammadev** [comment]
@SparcV8 *yammadev* es como un acrónimo de mi *nombre* + *developer*

**Comment by SparcV8** [comment]
:-O

averiguá acerca de YamaRASH...

(es un DEVA (Yama-DEV))

PD:
cultura oriental

xD

**Comment by yammadev** [comment]
@SparcV8 Muy interesante, le echaré un vistazo 👍
